version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/myapp_production
    ports:
      - '3001:3001'
    depends_on:
      - db

