default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  host: localhost
  port: 5432
  username: postgres
  password: postgres


test:
  <<: *default
  database: demo_test

production:
  <<: *default
  database: demo_production
  username: demo
  password: <%= ENV["DEMO_DATABASE_PASSWORD"] %>
